monitor:
- EPANO2
data_location:
- ../predictions/EPANO2
use_default_vars:
- TRUE
add_custom_vars:
- FALSE
custom_var_list:
- IF add_custom_vars is True, put the file name here.
data_save_location:
- ../test_data/process_data
train:
- TRUE
finalday:
- 20180101
csv_path:
- ~/shared_space/ci3_d_airpred/assembled_data/assembled_data.csv
rds_path:
- ~/shared_space/ci3_d_airpred/assembled_data/assembled_data.rds
imputation_models:
- ~/shared_space/ci3_d_airpred/assembled_data/imputation_models
mid_process_data:
- ~/shared_space/ci3_d_airpred/assembled_data/mid_process_data
training_data:
- ~/shared_space/ci3_d_airpred/assembled_data/mid_process_data/prepped.RDS
training_output:
- ~/shared_space/ci3_p_airpred/training_output
monitor_list:
- ~/shared_space/ci3_d_airpred/sites/AQRVPM25Site_North_America_Equidistant_Conic.mat
training_models:
- nn
- forest
- gradboost

