Monitor:
- EPANO2
Data_Location:
- ../predictions/EPANO2
Data_Save_Location:
- ../test_data/process_data
train:
- TRUE
finalday:
- 20180101
csv_path:
- ~/shared_space/ci3_d_airpred/assembled_data/assembled_data.csv
rds_path:
- ~/shared_space/ci3_d_airpred/assembled_data/assembled_data.rds
Imputation_Models:
- ~/shared_space/ci3_d_airpred/assembled_data/imputation_models
Mid_Process_Data:
-  ~/shared_space/ci3_d_airpred/assembled_data/mid_process_data
monitor_list:
- ~/shared_space/ci3_d_airpred/sites/AQRVPM25Site_North_America_Equidistant_Conic.mat
Training_Models:
- nn
- forest
- gradboost

