monitor:
- AQRVPM25
data_location:
- ~/shared_space/ci3_d_airpred/processed_data/AQRVPM25
input_file_type:
- mat
use_default_vars:
- TRUE
add_custom_vars:
- FALSE
custom_var_list:
- IF add_custom_vars is True, put the file name here.
data_save_location:
- ../test_data/process_data
train:
- TRUE
finalday:
- 20180101
csv_path:
- training_input/input.csv
rds_path:
- training_input/input.rds
imputation_models:
- mid_process_data/imputation_models
mid_process_data:
- mid_process_data
training_data:
- mid_process_data/prepped.RDS
training_output:
- training_output
monitor_list:
- ~/shared_space/ci3_d_airpred/sites/AQRVPM25Site_North_America_Equidistant_Conic.mat
date_var: date
site_var: site
output_var: MonitorData
impute: TRUE
impute_vars: default
impute_formula: default
normalize: TRUE
transform: TRUE
pre_generated_weights: FALSE
weight_matrix_paths:
- path_1
- path_2
- path_3
training_models:
- nn
- forest
- gradboost
two_stage: FALSE
predict_data:
- predictions/input/predict_input.csv
predict_mid_process:
- predictions/mid_process
predict_output:
- predictions/output

