deeplearning:
   epochs:
     - 40
     - 50
     - 75
   hidden:
     -
       - 210
       - 210
     -
       - 150
       - 150
     -
       - 250
       - 250
   l1:
     - 0.0001
     - 0.00001
   activation:
     - Rectifier

randomForest:
   ntrees:
     - 100
     - 200
     - 300
   max_depth: 420
