deeplearning:
   nfolds:
     - 10
   epochs:
     - 40
     - 50
     - 75
   hidden:
     -
       - 210
       - 210
     -
       - 150
       - 150
     -
       - 250
       - 250
   l1:
     - 0.0001
     - 0.00001
   activation:
     - Rectifier

randomForest:
   nfolds:
     - 10
   ntrees:
     - 100
     - 200
     - 300
     - 400
     - 500
     - 600
     - 700
     - 800
     - 900
     - 1000
   max_depth:
     - 6
     - 7
     - 8
     - 9
     - 10
     - 11
     - 12
     - 13
     - 14
     - 15
gbm:
  nfolds:
    - 10
  ntrees:
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
    - 350
    - 400
    - 450
    - 500
  max_depth:
    - 3
    - 4
    - 5
    - 6
